Our vision/story
Legendarius-K/parking_time pull request #23
Opened 2024-06-17 14:05 UTC by svanen99

2024-06-17 14:47 UTC, Legendarius-K requested changes
Looks awesome! A thinner font on the text then done!

2024-06-24 07:48 UTC, Legendarius-K approved these changes
CR approved! @svanen99

2024-06-24 11:34 UTC, timdeckel commented on src/components/OurVisionStory/index.tsx
there is some code here that is commented out and looks like legacy code. some clean up could be nice.

2024-06-24 11:35 UTC, timdeckel approved these changes
code is tested and checked. fix the commented code please. other that it looks good!

2024-06-25 08:40 UTC, merged